FROM node:20-alpine AS builder

WORKDIR /app

COPY package*.json tsconfig.base.json ./
COPY packages/ ./packages/
COPY apps/teacher-web/ ./apps/teacher-web/

RUN npm install
RUN npm run build --workspace=@janbhasha/domain
RUN npm run build --workspace=@janbhasha/ui
RUN npm run build --workspace=janbhasha-teacher-web

FROM nginx:alpine AS runner

COPY --from=builder /app/apps/teacher-web/dist /usr/share/nginx/html
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
